DROP TABLE IF EXISTS Operos_artistas, Baleto_artistas, Dalyvauja, Spektaklis, Pasirodymas, Repertuaras CASCADE;
DROP VIEW IF EXISTS Balu_skaiciuokle, Spektakliu_tarifu_vidurkiai;
-- SET search_path TO adkl9920

CREATE TABLE Operos_artistas (
    Id          SMALLINT      GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    Rangas      VARCHAR(7)    DEFAULT 'Coro',
    Vardas      VARCHAR(12)   NOT NULL,
    Pavarde     VARCHAR(20)   NOT NULL,
    Lytis       CHAR(3)       NOT NULL,
    Gimimas     DATE          NOT NULL,
    Isidarbino  DATE          NOT NULL,
    Balsas      VARCHAR(13)   NOT NULL,

    CONSTRAINT balso_tipas CHECK (
        (Rangas = 'Solista' AND Lytis = 'Mot' AND Balsas IN ('Soprano', 'Mezzo-Soprano', 'Contralto'))
        OR
        (Rangas = 'Solista' AND Lytis = 'Vyr' AND Balsas IN ('Countertenor', 'Tenor', 'Baritone', 'Bass-Baritone', 'Bass'))
        OR
        (Rangas = 'Coro' AND Balsas IN ('Soprano', 'Alto', 'Tenor', 'Bass'))
    ),
    CONSTRAINT Lytis_check CHECK (
        Lytis IN ('Vyr', 'Mot')
    ),
    CONSTRAINT isidarbino_metai CHECK (EXTRACT(YEAR FROM Isidarbino) > 1974)
);

CREATE TABLE Baleto_artistas (
    Id          SMALLINT      GENERATED BY DEFAULT AS IDENTITY (START WITH 2000) PRIMARY KEY,
    Rangas      VARCHAR(15)   DEFAULT 'Corps de ballet',
    Vardas      VARCHAR(12)   NOT NULL,
    Pavarde     VARCHAR(20)   NOT NULL,
    Lytis       CHAR(3)       NOT NULL,
    Gimimas     DATE          NOT NULL,
    Isidarbino  DATE          NOT NULL,
    Ugis        SMALLINT      NOT NULL,

    CONSTRAINT teisingi_rangai CHECK (
        Rangas IN ('Prima ballerina', 'Premier danseur', 'Sujet', 'Coryphee', 'Corps de ballet')
    ),
    CONSTRAINT prima_gimines CHECK (
        (Lytis = 'Mot' AND Rangas = 'Prima ballerina')
        OR
        (Lytis = 'Vyr' AND Rangas = 'Premier danseur')
        OR
        Rangas IN ('Sujet', 'Coryphee', 'Corps de ballet')
    ),
    CONSTRAINT isidarbino_metai CHECK (EXTRACT(YEAR FROM Isidarbino) > 1974)
);

CREATE TABLE Spektaklis (
    Id             SMALLINT       GENERATED BY DEFAULT AS IDENTITY (START WITH 300) PRIMARY KEY,
    Pavadinimas    VARCHAR(32)    NOT NULL,
    Veiksmu_sk     SMALLINT       NOT NULL,
    Tipas          VARCHAR(2)     NOT NULL,
    Stilius        VARCHAR(32)    NOT NULL,
    CONSTRAINT teisingas_tipas CHECK (
        Tipas IN ('O', 'B', 'OB')
    )
);

CREATE TABLE Repertuaras (
    Sezonas       SMALLINT       NOT NULL,
    Pradzia_sez    SMALLINT       NOT NULL,
    Pabaiga_sez    SMALLINT       NOT NULL,
    PRIMARY KEY (Sezonas)
);

CREATE TABLE Dalyvauja (
    Id                      SMALLINT          GENERATED BY DEFAULT AS IDENTITY (START WITH 5000) PRIMARY KEY,
    Operos_artisto_id       SMALLINT,
    Baleto_artisto_id       SMALLINT,
    Spektaklio_id           SMALLINT          NOT NULL,
    Uzimtumas               VARCHAR(12)      NOT NULL,
    Vaidmuo                 VARCHAR(20)       NOT NULL,
    Balai                   DECIMAL(3,1)                  NOT NULL,
    CONSTRAINT f_Opera FOREIGN KEY (Operos_artisto_id) REFERENCES Operos_artistas(id) ON DELETE CASCADE,
    CONSTRAINT f_Baletas FOREIGN KEY (Baleto_artisto_id) REFERENCES Baleto_artistas(id) ON DELETE CASCADE,
    CONSTRAINT f_Spektaklis FOREIGN KEY (Spektaklio_id) REFERENCES Spektaklis(id) ON DELETE CASCADE,

    CONSTRAINT uzimtumas_format_check CHECK (Uzimtumas ~ '^\d+(,\d+)*$'),
    CONSTRAINT opera_or_baletas CHECK (
        (Operos_artisto_id IS NOT NULL AND Baleto_artisto_id IS NULL)
        OR
        (Baleto_artisto_id IS NOT NULL AND Operos_artisto_id IS NULL)
    )
);

CREATE TABLE Pasirodymas (
    Pasirodymo_data     TIMESTAMP,
    Spektaklio_id          SMALLINT       NOT NULL,
    Repertuaras          SMALLINT       NOT NULL,
    Tarifas             SMALLINT       NOT NULL,
    Ziurovai            VARCHAR(14)    NOT NULL,
    CONSTRAINT f_Spektaklis FOREIGN KEY (Spektaklio_id) REFERENCES Spektaklis(id) ON DELETE CASCADE,
    CONSTRAINT f_Repertuaras FOREIGN KEY (Repertuaras) REFERENCES Repertuaras(Sezonas) ON DELETE CASCADE,
    CONSTRAINT kam_skirta CHECK (
        Ziurovai IN ('Vaikams', 'Suaugusiesiems', 'Visiems')
    ),
 
    PRIMARY KEY (Pasirodymo_data)
);


CREATE OR REPLACE FUNCTION patikrinti_baleto_grupes_ugius()
RETURNS TRIGGER AS $$
DECLARE
    min_ugis SMALLINT;
    max_ugis SMALLINT;
    new_ugis SMALLINT;
BEGIN
    IF NEW.Baleto_artisto_id IS NOT NULL THEN

        SELECT Ugis
          INTO new_ugis
          FROM Baleto_artistas
         WHERE Id = NEW.Baleto_artisto_id;
         
        SELECT MIN(ba.Ugis), 
        			MAX(ba.Ugis)
          INTO min_ugis, max_ugis
          FROM Dalyvauja d
          JOIN Baleto_artistas ba ON ba.Id = d.Baleto_artisto_id
         WHERE d.Spektaklio_id = NEW.Spektaklio_id
           AND d.Vaidmuo = NEW.Vaidmuo
           AND d.Id <> NEW.Id;

        IF min_ugis IS NOT NULL AND max_ugis IS NOT NULL THEN
            IF new_ugis < min_ugis THEN
                min_ugis := new_ugis;
            END IF;
            IF new_ugis > max_ugis THEN
                max_ugis := new_ugis;
            END IF;

            IF (max_ugis - min_ugis) > 10 THEN
                RAISE EXCEPTION 'Baleto grupės (vaidmuo "%", spektaklis %) ūgio skirtumas viršija 10cm.',
                                NEW.Vaidmuo, NEW.Spektaklio_id;
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_patikrinti_baleto_grupes_ugius
BEFORE INSERT OR UPDATE ON Dalyvauja
FOR EACH ROW
EXECUTE FUNCTION patikrinti_baleto_grupes_ugius();



CREATE OR REPLACE FUNCTION patikrinti_dalyviu_tipa()
RETURNS TRIGGER AS $$
DECLARE
    spektaklio_tipas VARCHAR(2);
BEGIN
    SELECT Tipas INTO spektaklio_tipas
    FROM Spektaklis
    WHERE Id = NEW.Spektaklio_id;

    IF spektaklio_tipas = 'B' THEN
        IF NEW.Baleto_artisto_id IS NULL OR NEW.Operos_artisto_id IS NOT NULL THEN
            RAISE EXCEPTION 'Gali dalyvauti tik baleto artistai (Spektaklis Id=%).', NEW.Spektaklio_id;
        END IF;
    ELSIF spektaklio_tipas = 'O' THEN
        IF NEW.Operos_artisto_id IS NULL OR NEW.Baleto_artisto_id IS NOT NULL THEN
            RAISE EXCEPTION 'Gali dalyvauti tik operos artistai (Spektaklis Id=%).', NEW.Spektaklio_id;
        END IF;
      END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_patikrinti_dalyviu_tipa
BEFORE INSERT OR UPDATE ON Dalyvauja
FOR EACH ROW
EXECUTE FUNCTION patikrinti_dalyviu_tipa();


CREATE OR REPLACE FUNCTION patikrinti_spektaklio_laika()
RETURNS TRIGGER AS $$
DECLARE
    savaites_diena INT;
    pasirodymo_laikas TIME;
BEGIN

    savaites_diena := EXTRACT(DOW FROM NEW.Pasirodymo_data);
    pasirodymo_laikas := NEW.Pasirodymo_data::TIME;
    
    IF savaites_diena = 1 THEN
        RAISE EXCEPTION 'Spektaklis negali vykti pirmadienį.';
    END IF;

    IF NEW.Ziurovai = 'Suaugusiesiems' THEN
        IF savaites_diena = 7 THEN
            IF pasirodymo_laikas <> '18:00' THEN
                RAISE EXCEPTION 'Spektaklis suaugusiesiems sekmadieniais turi prasidėti tik 18:00.';
          END IF;
        ELSE
            IF pasirodymo_laikas <> '18:30' THEN
                RAISE EXCEPTION 'Spektaklis suaugusiesiems turi prasidėti tik 18:30.';
            END IF;
    END IF;

    ELSIF NEW.Ziurovai = 'Visiems' THEN
    IF savaites_diena = 7 THEN
        IF NOT (pasirodymo_laikas >= '10:00' AND pasirodymo_laikas <= '18:00') THEN
            RAISE EXCEPTION 'Spektaklis visiems sekmadieniais gali prasideti tik nuo 10:00 iki 18:00.';
        END IF;
    ELSE
        IF NOT (pasirodymo_laikas >= '10:00' AND pasirodymo_laikas <= '18:30') THEN
            RAISE EXCEPTION 'Spektaklis visiems gali prasideti tik nuo 10:00 iki 18:30.';
        END IF;
    END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_patikrinti_spektaklio_laika
BEFORE INSERT OR UPDATE ON Pasirodymas
FOR EACH ROW
EXECUTE FUNCTION patikrinti_spektaklio_laika();

-- CREATE UNIQUE INDEX idx_pasirodymas_pasirodymo_data
-- ON Pasirodymas (Pasirodymo_data);

CREATE INDEX idx_vaidmuo
ON Dalyvauja (Vaidmuo);


CREATE VIEW Balu_skaiciuokle AS
SELECT 
    CASE WHEN D.Operos_artisto_id IS NOT NULL THEN O.Vardas ELSE BA.Vardas END AS Vardas,
    CASE WHEN D.Operos_artisto_id IS NOT NULL THEN O.Pavarde ELSE BA.Pavarde END AS Pavarde,
    SUM(D.Balai) AS suma,
    CASE WHEN D.Operos_artisto_id IS NOT NULL THEN 'O' ELSE 'B' END AS artisto_tipas
FROM Dalyvauja D
LEFT JOIN Operos_artistas O ON D.Operos_artisto_id = O.Id
LEFT JOIN Baleto_artistas BA ON D.Baleto_artisto_id = BA.Id
JOIN Pasirodymas P ON P.Spektaklio_id = D.Spektaklio_id
WHERE EXTRACT(MONTH FROM P.Pasirodymo_data) = EXTRACT(MONTH FROM (CURRENT_TIMESTAMP - INTERVAL '0 month'))
GROUP BY
    CASE WHEN D.Operos_artisto_id IS NOT NULL THEN O.Vardas ELSE BA.Vardas END,
    CASE WHEN D.Operos_artisto_id IS NOT NULL THEN O.Pavarde ELSE BA.Pavarde END,
    CASE WHEN D.Operos_artisto_id IS NOT NULL THEN 'O' ELSE 'B' END;


CREATE VIEW Spektakliu_tarifu_vidurkiai AS
SELECT A.Pavadinimas,
       COUNT(B.Pasirodymo_data) AS Pasirodymu_Skaicius,
       AVG(B.Tarifas) AS Vidutinis_Tarifas,
       SUM(B.Tarifas * 984) AS vidutiniskai_gaunama_is_tarifu
FROM Spektaklis A
JOIN Pasirodymas B ON A.Id = B.Spektaklio_id
WHERE EXTRACT(MONTH FROM B.Pasirodymo_data) = EXTRACT(MONTH FROM (CURRENT_TIMESTAMP - INTERVAL '0 month'))
GROUP BY A.Pavadinimas;



INSERT INTO Operos_artistas (Vardas, Pavarde, Lytis, Gimimas, Isidarbino, Balsas, Rangas)
VALUES
    ('Rafailas', 'Karpis', 'Vyr', '1983-04-10', '2007-01-01', 'Tenor', 'Solista'),
    ('Monika', 'Pleskyte', 'Mot', '1995-08-22', '2015-03-15', 'Soprano', 'Solista'),
    ('Karolis', 'Kasiuba', 'Vyr', '2000-12-01', '2010-06-20', 'Tenor', 'Solista'),
    ('Steponas ', 'Zonys', 'Vyr', '1997-07-15', '2015-04-10', 'Baritone', 'Solista');

INSERT INTO Baleto_artistas (Vardas, Pavarde, Lytis, Gimimas, Isidarbino, Ugis, Rangas)
VALUES
    ('Olesia', 'Saitanova', 'Mot', '2000-11-14', '2019-08-15', 165, 'Prima ballerina' ),
    ('Jonas', 'Laucius', 'Vyr', '1998-11-30', '2012-01-05', 185, 'Premier danseur'),
    ('Greta', 'Gylyte', 'Mot', '1985-02-10', '2008-05-20', 175, 'Sujet'),
    ('Adrian', 'Klimasevski', 'Vyr', '2004-09-29', '2023-08-05', 178, 'Corps de ballet'),
    ('Charlotte', 'Lejeune', 'Mot', '2000-02-10', '2020-05-20', 175, 'Coryphee'),
    ('Laimis', 'Roslekas', 'Vyr', '1980-05-22', '2000-08-05', 178, 'Sujet'),
    ('Aistis', 'Kavaliauskas', 'Vyr', '1995-07-22', '2018-12-05', 188, 'Corps de ballet'),
    ('Mantas', 'Daraskevicius', 'Vyr', '1981-01-12', '2000-05-05', 178, 'Sujet');


INSERT INTO Spektaklis (Pavadinimas, Veiksmu_sk, Tipas, Stilius)
VALUES
    ('Uzburtos Akys', 2, 'B', 'Neoklasikinis baletas'),
    ('Arlekino Milijonai', 2, 'B', 'Neoklasikinis baletas'),
    ('Dievo avinelis', 3, 'OB', 'Klasikine lietuviu opera'),
    ('Operu triptikas', 3, 'O', 'Trys vienveiksmes operos');

INSERT INTO Repertuaras (Sezonas, Pradzia_sez, Pabaiga_sez)
VALUES
    (104, 2023, 2024),
    (105, 2024, 2025),
    (106, 2025, 2026);

INSERT INTO Pasirodymas (Spektaklio_id, Repertuaras, Pasirodymo_data, Tarifas, Ziurovai)
VALUES
    (300, 105, '2024-12-08 12:00:00', 3, 'Vaikams'),
    (301, 105, '2024-12-11 18:30:00', 10, 'Visiems'),
    (301, 105, '2024-12-12 18:30:00', 10, 'Visiems'),
    (301, 105, '2024-12-13 18:30:00', 10, 'Visiems'),
    (301, 105, '2024-12-14 18:30:00', 15, 'Visiems'),
    (301, 105, '2024-12-15 18:00:00', 20, 'Visiems'),
    (302, 105, '2024-10-17 18:30:00', 13, 'Suaugusiesiems'),
    (302, 105, '2024-10-18 18:30:00', 16, 'Suaugusiesiems'),
    (302, 105, '2024-10-19 18:30:00', 20, 'Suaugusiesiems'),
    (303, 105, '2024-12-07 18:30:00', 30, 'Suaugusiesiems');


INSERT INTO Dalyvauja (Baleto_artisto_id, Spektaklio_id, Uzimtumas, Vaidmuo, Balai)
VALUES
    (2003, 300, '1,2', 'Robotas', 2.5),
    (2000, 301, '1,2', 'Pjerete', 8.5),
    (2001, 301, '1,2', 'Pjero', 7.5),
    (2003, 302, '1,2,3', 'Stribas', 3),
    (2005, 302, '1,2,3', 'Stribas', 3),
    (2006, 302, '1,2,3', 'Stribas', 3),
    (2007, 302, '1,2,3', 'Stribas', 3);
    
    
INSERT INTO Dalyvauja (Operos_artisto_id, Spektaklio_id, Uzimtumas, Vaidmuo, Balai)
VALUES
    (1000, 302, '1,2,3', 'Vyras', 10),
    (1001, 302, '1,2', 'Dvasia', 8.5);


CREATE MATERIALIZED VIEW top_Artistai AS
WITH artistu_rezultatai AS (
    SELECT
        CASE WHEN O.id IS NOT NULL THEN O.id ELSE BA.id END AS Id,
        CASE WHEN O.id IS NOT NULL THEN O.Vardas ELSE BA.Vardas END AS Vardas,
        CASE WHEN O.id IS NOT NULL THEN O.Pavarde ELSE BA.Pavarde END AS Pavarde,
        CASE WHEN O.id IS NOT NULL THEN 'O' ELSE 'B' END AS Artisto_Tipas,
        SUM(D.Balai) AS Viso_Balu
    FROM Dalyvauja D
    LEFT JOIN Operos_artistas O ON O.Id = D.Operos_artisto_id
    LEFT JOIN Baleto_artistas BA ON BA.Id = D.Baleto_artisto_id
    JOIN Pasirodymas P ON P.Spektaklio_id = D.Spektaklio_id
    WHERE EXTRACT('year' FROM P.Pasirodymo_data) = EXTRACT('year' FROM CURRENT_DATE - INTERVAL '0 year')
    GROUP BY
        CASE WHEN O.id IS NOT NULL THEN O.id ELSE BA.id END,
        CASE WHEN O.id IS NOT NULL THEN O.Vardas ELSE BA.Vardas END,
        CASE WHEN O.id IS NOT NULL THEN O.Pavarde ELSE BA.Pavarde END,
        CASE WHEN O.id IS NOT NULL THEN 'O' ELSE 'B' END
)
SELECT *
FROM (
  SELECT
    RANK() OVER (ORDER BY Viso_Balu DESC) AS vieta,
    Vardas,
    Pavarde,
    Artisto_Tipas,
    Viso_Balu
  FROM artistu_rezultatai
) AS ranked
WHERE ranked.vieta <= 5;


CREATE OR REPLACE FUNCTION keiciant_repertuara()
RETURNS TRIGGER AS $$
DECLARE
BEGIN   
    REFRESH MATERIALIZED VIEW top_Artistai;
        
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_keiciant_repertuara
BEFORE INSERT OR UPDATE ON Repertuaras
FOR EACH ROW
EXECUTE FUNCTION keiciant_repertuara();


SELECT * FROM Operos_artistas;

SELECT * FROM Baleto_artistas;

SELECT * FROM Spektaklis;

SELECT * FROM Repertuaras;



SELECT * FROM Pasirodymas;

SELECT * FROM Dalyvauja;

SELECT * FROM top_Artistai;

SELECT * FROM Spektakliu_tarifu_vidurkiai;

SELECT * FROM Balu_skaiciuokle;

